---
title: "Data Wrangling Final Project"
author: "Peter J. Ehmann"
date: "Due: 5/6/2019"
output: html_document
---

```{r setup, include = FALSE}
library(broom)
library(jsonlite)
library(knitr)
library(rvest)
library(tidyverse)
library(xml2)
opts_chunk$set(echo = FALSE)
```

<br>

### Get smoking data. JSON.

```{r 2}
smoking_rates <- "https://chronicdata.cdc.gov/resource/gx47-p4ij.json" %>% 
  fromJSON() %>% 
  as_tibble() %>% 
  rename(state = locationdesc, abbr = locationabbr, year = year, percent = data_value) %>% 
  select(state, abbr, year, percent) %>% 
  group_by(state, abbr) %>% 
  nest(.key = smoking_rate) %>% 
  filter(abbr != "PR",
         abbr != "GU") %>% 
  arrange(state)
```

<br>

### Get state taxation data. JSON.

```{r 3}
tax <- "https://chronicdata.cdc.gov/resource/7uzt-fasa.json" %>% 
  fromJSON() %>% 
  as.data.frame()
```

<br>

### Get state taxation data. HTML for wikipedia list.

```{r 3}
states_html <- read_html("https://simple.wikipedia.org/wiki/List_of_regions_of_the_United_States")

states <- states_html %>% 
  html_nodes(xpath = "//div/ul/li/ul/li/ul/li") %>% 
  html_text()

divisions <- states_html %>% 
  html_nodes(xpath = "//div/div/div/div/ul/li/ul/li") %>% 
  html_text()

regions <- states_html %>% 
  html_nodes(xpath = "//div/div/div/div/ul/li") %>% 
  html_text()

tbl <- as_tibble(data.frame(matrix(nrow = length(list_of_states), ncol = 3)))
colnames(tbl) <- c("state", "region", "division")
tbl[,1] <- list_of_states

division_names <- divisions %>% 
  str_extract(., "\\((.*)\\)") %>% 
  str_extract(., "[\\w+\\s?]+")

division_counts <- divisions %>% 
  str_count(., "\n")

division_list = ""
for (i in 1:length(division_names)) {
  division_list <- c(division_list, (rep(division_names[i], division_counts[i])))
}

division_list <- division_list[-1]
tbl[,3] <- division_list

region_names <- regions %>% 
  .[1:4] %>% 
  str_extract(., "\\((.*)\\)") %>% 
  str_extract(., "[\\w+\\s?]+")

region_counts <- regions %>% 
  .[1:4] %>% 
  str_count(., "\n")

divisions_per_region <- regions %>% 
  .[1:4] %>% 
  str_count(., "Division")

region_list = ""
for (i in 1:length(region_names)) {
  region_list <- c(region_list, (rep(region_names[i], region_counts[i]-divisions_per_region[i])))
}

region_list <- region_list[-1]
tbl[,2] <- region_list

tbl <- tbl %>% arrange(state)
```

<br>

```{r merge_datasets}
df_clean <- merge(smoking_rates, tbl, by = "state") %>%
  unnest()
```

### Write tidied dataset as a .csv to current directory.

```{r write_csv}
df_clean %>% write_csv("smoking_data.csv")
```

<br>

### Read in provided .csv from GitHub repository.

```{r 4}
data <- read_csv("https://raw.githubusercontent.com/peter-ehmann/Data_Wrangling_Project_S2019/master/smoking_data.csv")
```

<br>

### Display information about the packages used, their versions, and the version of R that was used.

```{r sessionInfo}
devtools::sessionInfo()
```

